More Brewfile goodies!

diff --git a/install b/install
--- a/install
+++ b/install
@@ -30,6 +30,17 @@ done < .external
 
 brew bundle --global
 
+grep ^cask ~/.Brewfile | awk '{print $2}' | sed "s/[\"\"']//g" | while read cask; do
+  case "$cask" in
+    iterm2 ) app="iterm" ;;
+    virtualbox-extension-pack | vagrant ) continue ;;
+    * ) app="${cask//-/ }" ;;
+  esac
+  if ! ls /Applications ~/Applications | grep -qi "$app"; then
+    echo "warning: \`$cask' not found in /Applications" >&2
+  fi
+done
+
 if ! [ -e ~/.vim ]; then
   git clone https://github.com/mislav/vimfiles ~/.vim
   cd ~/.vim
